#!/bin/bash
#
# Functions to override if using ml2 plugin
# -----------------------------------------

function neutron_plugin_setup_interface_driver {
    local conf_file=$1
    iniset $conf_file DEFAULT interface_driver neutron.agent.linux.interface.MidonetInterfaceDriver
}

function configure_neutron_midonet {
    echo "Configuring ML2 for Midonet"
    populate_ml2_config /$Q_PLUGIN_CONF_FILE MIDONET midonet_uri=$MIDONET_API_URL
    populate_ml2_config /$Q_PLUGIN_CONF_FILE MIDONET username=$Q_ADMIN_USERNAME
    populate_ml2_config /$Q_PLUGIN_CONF_FILE MIDONET password=$SERVICE_PASSWORD
    populate_ml2_config /$Q_PLUGIN_CONF_FILE MIDONET project_id=$SERVICE_TENANT_NAME
    populate_ml2_config /$Q_PLUGIN_CONF_FILE MIDONET client=$MIDONET_CLIENT
}
