#!/bin/bash
#
# Functions to override if using ml2 plugin
# -----------------------------------------

function neutron_plugin_setup_interface_driver {
    local conf_file=$1
    iniset $conf_file DEFAULT interface_driver midonet
}

function configure_neutron_midonet {
    echo "Configuring ML2 for Midonet"
    iniset /$Q_PLUGIN_CONF_FILE MIDONET midonet_uri $MIDONET_API_URL
    iniset /$Q_PLUGIN_CONF_FILE MIDONET username $Q_ADMIN_USERNAME
    iniset /$Q_PLUGIN_CONF_FILE MIDONET password $SERVICE_PASSWORD
    iniset /$Q_PLUGIN_CONF_FILE MIDONET project_id $SERVICE_TENANT_NAME
    iniset /$Q_PLUGIN_CONF_FILE MIDONET client $MIDONET_CLIENT
    iniset /$Q_PLUGIN_CONF_FILE MIDONET cluster_ip $MIDONET_SERVICE_HOST
    iniset /$Q_PLUGIN_CONF_FILE MIDONET cluster_port $TOPOLOGY_API_PORT

    if ! is_neutron_legacy_enabled; then
        neutron_service_plugin_class_add midonet_l3
        iniset /$Q_PLUGIN_CONF_FILE ml2 mechanism_drivers midonet
        iniset /$Q_PLUGIN_CONF_FILE ml2 type_drivers midonet,uplink
        iniset /$Q_PLUGIN_CONF_FILE ml2 tenant_network_types midonet
        iniset /$Q_PLUGIN_CONF_FILE ml2 external_network_type midonet
    fi
}

function install_neutron_midonet {
    :
}
