#!/bin/bash
#
# Common functions for devstack
# -----------------------------

function create_nova_conf_midonet {
    if [[ "${MIDONET_USE_METADATA}" == "True" ]]; then
        iniset $NOVA_CONF neutron service_metadata_proxy "True"
        if is_service_enabled n-cells; then
            iniset $NOVA_CELLS_CONF neutron service_metadata_proxy "True"
        fi
    fi
}

function neutron_plugin_create_nova_conf {
    :
}

function is_neutron_ovs_base_plugin {
    # 0 means True here
    return 1
}

function neutron_plugin_configure_debug_command {
    :
}

function neutron_plugin_install_agent_packages {
    :
}

function neutron_plugin_configure_dhcp_agent {
    DHCP_DRIVER=${DHCP_DRIVER:-"midonet.neutron.agent.midonet_driver.DhcpNoOpDriver"}
    neutron_plugin_setup_interface_driver $Q_DHCP_CONF_FILE
    iniset $Q_DHCP_CONF_FILE DEFAULT dhcp_driver $DHCP_DRIVER
    iniset $Q_DHCP_CONF_FILE DEFAULT use_namespaces True
    iniset $Q_DHCP_CONF_FILE DEFAULT enable_isolated_metadata True
}

function configure_midonet_cli {
    local MIDONETRC_FILE="${HOME}/.midonetrc"

    iniset $MIDONETRC_FILE cli api_url $MIDONET_API_URL
    iniset $MIDONETRC_FILE cli username admin
    iniset $MIDONETRC_FILE cli password $ADMIN_PASSWORD
    iniset $MIDONETRC_FILE cli project_id admin
}
