#!/bin/bash

# Use MidoNet binary packages rather than devmido
# NOTE(yamamoto): This doesn't support java7, which is used by MidoNet < 5.0
MIDONET_USE_PACKAGE=${MIDONET_USE_PACKAGE:-True}
MIDNOET_DEB_URI=${MIDNOET_DEB_URI:-http://builds.midonet.org/devstack}
MIDNOET_DEB_SUITE=${MIDNOET_DEB_SUITE:-unstable}
MIDNOET_DEB_COMPONENT=${MIDNOET_DEB_COMPONENT:-main}

# MidoNet repo
# Ignored if MIDONET_USE_PACKAGE=True
MIDONET_REPO=${MIDONET_REPO:-http://github.com/midonet/midonet.git}
MIDONET_BRANCH=${MIDONET_BRANCH:-master}
MIDONET_DIR=${MIDONET_DIR:-$DEST/midonet}

# This flag indicates to the MidoNet agent to use ZOOM (MN v2)
MIDONET_USE_ZOOM=${MIDONET_USE_ZOOM:-True}

# Set up cassndra (for flow state etc)
# Ignored if MIDONET_USE_PACKAGE!=True
MIDONET_USE_CASSANDRA=${MIDONET_USE_CASSANDRA:-False}

# Use uplink network for "fake" uplink
# MIDONET_USE_UPLINK=False is incompatible with MIDONET_USE_PACKAGE=True
MIDONET_USE_UPLINK=${MIDONET_USE_UPLINK:-True}
# Configure NAT for public network.
# You need to configure PUBLIC_INTERFACE properly.
MIDONET_USE_UPLINK_NAT=${MIDONET_USE_UPLINK_NAT:-False}

# MidoNet service endpoint configuration
MIDONET_SERVICE_API_PORT=${MIDONET_SERVICE_API_PORT:-8181}
MIDONET_SERVICE_PROTOCOL=${MIDONET_SERVICE_PROTOCOL:-$SERVICE_PROTOCOL}
MIDONET_SERVICE_HOST=${MIDONET_SERVICE_HOST:-$SERVICE_HOST}
MIDONET_API_URL="${MIDONET_SERVICE_PROTOCOL}://${MIDONET_SERVICE_HOST}:${MIDONET_SERVICE_API_PORT}/midonet-api"

# MidoNet Plugin and Client
MIDONET_PLUGIN=${MIDONET_PLUGIN:-midonet_v2}
MIDONET_CLIENT=${MIDONET_CLIENT:-midonet.neutron.client.api.MidonetApiClient}

# Midonet metadata service
MIDONET_USE_METADATA=${MIDONET_USE_METADATA:-False}
MIDONET_NOVA_METADATA_URL=${MIDONET_NOVA_METADATA_URL:-http://${Q_META_DATA_IP}:8775}
MIDONET_METADATA_SHARED_SECRET=${MIDONET_METADATA_SHARED_SECRET:-}

# Use Keystone for MidoNet API auth.  If False, use a mock.
MIDONET_USE_KEYSTONE=${MIDONET_USE_KEYSTONE:-True}

# create the fake uplink by default
MIDONET_CREATE_FAKE_UPLINK=${MIDONET_CREATE_FAKE_UPLINK:-True}

#
# Set all the devstack ENV VARS needed to run midonet in a full OpenStack
# deployment setting
#

# Routers should be per tenant
Q_L3_ROUTER_PER_TENANT=True

# Enable L3
Q_L3_ENABLED=True

# Use IPv4
IP_VERSION=4

# Tempest options
IPV6_ENABLED=False

NETWORK_API_EXTENSIONS=agent,binding,dhcp_agent_scheduler,external-net
NETWORK_API_EXTENSIONS+=,ext-gw-mode,extra_dhcp_opts,quotas,router
NETWORK_API_EXTENSIONS+=,security-group,subnet_allocation
NETWORK_API_EXTENSIONS+=,network-ip-availability,auto-allocated-topology
NETWORK_API_EXTENSIONS+=,timestamp_core,tag,service-type,rbac-policies
NETWORK_API_EXTENSIONS+=,standard-attr-description
NETWORK_API_EXTENSIONS+=,pagination
NETWORK_API_EXTENSIONS+=,sorting
NETWORK_API_EXTENSIONS+=,project-id
if [[ "$MIDONET_USE_ZOOM" == "True" ]]; then
    NETWORK_API_EXTENSIONS+=,allowed-address-pairs,extraroute,port-security
    NETWORK_API_EXTENSIONS+=,router-interface-fip
    if is_service_enabled q-fwaas; then
        NETWORK_API_EXTENSIONS+=,fwaas,fwaasrouterinsertion
    fi
fi
if is_service_enabled neutron-vpnaas; then
    NETWORK_API_EXTENSIONS+=,vpnaas
fi
if is_service_enabled taas; then
    NETWORK_API_EXTENSIONS+=,taas
fi
if is_service_enabled q-qos; then
    NETWORK_API_EXTENSIONS+=,qos
fi

# Don't let mido.sh configure the logging
CONFIGURE_LOGGING=False
