#!/bin/bash

# MidoNet repo
MIDONET_REPO=${MIDONET_REPO:-http://github.com/midonet/midonet.git}
MIDONET_BRANCH=${MIDONET_BRANCH:-master}
MIDONET_DIR=${MIDONET_DIR:-$DEST/midonet}

# This flag indicates to the MidoNet agent to use ZOOM (MN v2)
MIDONET_USE_ZOOM=${MIDONET_USE_ZOOM:-True}

# MidoNet service endpoint configuration
MIDONET_SERVICE_API_PORT=${MIDONET_SERVICE_API_PORT:-8181}
MIDONET_SERVICE_PROTOCOL=${MIDONET_SERVICE_PROTOCOL:-$SERVICE_PROTOCOL}
MIDONET_SERVICE_HOST=${MIDONET_SERVICE_HOST:-$SERVICE_HOST}
MIDONET_API_URL="${MIDONET_SERVICE_PROTOCOL}://${MIDONET_SERVICE_HOST}:${MIDONET_SERVICE_API_PORT}/midonet-api"

# MidoNet Plugin and Client
MIDONET_PLUGIN=${MIDONET_PLUGIN:-midonet.neutron.plugin_v2.MidonetPluginV2}
MIDONET_CLIENT=${MIDONET_CLIENT:-midonet.neutron.client.api.MidonetApiClient}

# create the fake uplink by default
MIDONET_CREATE_FAKE_UPLINK=${MIDONET_CREATE_FAKE_UPLINK:-True}

#
# Set all the devstack ENV VARS needed to run midonet in a full OpenStack
# deployment setting
#

# Routers should be per tenant
Q_L3_ROUTER_PER_TENANT=True

# Enable L3
Q_L3_ENABLED=True

# Use IPv4
IP_VERSION=4

# Set the database driver for sqlalchemy
SQLALCHEMY_DATABASE_DRIVER=${SQLALCHEMY_DATABASE_DRIVER:-mysqlconnector}

# Tempest options
IPV6_ENABLED=False

NETWORK_API_EXTENSIONS=agent,binding,dhcp_agent_scheduler,external-net
NETWORK_API_EXTENSIONS+=,ext-gw-mode,extra_dhcp_opts,quotas,router
NETWORK_API_EXTENSIONS+=,security-group
if [[ "$MIDONET_USE_ZOOM" == "True" ]]; then
    NETWORK_API_EXTENSIONS+=,allowed-address-pairs,extraroute,port-security
fi

# Don't let mido.sh configure the logging
CONFIGURE_LOGGING=False
