#!/bin/bash

# A trimmed copy of devstack/lib/tempest
# for bug/1582119

function configure_tempest_midonet {
    local public_network_id

    public_network_id=$(neutron net-list | grep $PUBLIC_NETWORK_NAME | \
        awk '{print $2}')

    iniset $TEMPEST_CONFIG network public_network_id "$public_network_id"
}
