- project:
    templates:
      # NOTE(ralonsoh): removed until the job is fixed.
      #- check-requirements
      - openstack-python3-victoria-jobs-neutron
      # NOTE(ralonsoh): removed until the job is fixed.
      #- publish-openstack-docs-pti
      # NOTE(ralonsoh): removed until the job is fixed.
      #- release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - openstack-tox-py36:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - openstack-tox-py38:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - openstack-tox-cover:
            voting: false
            required-projects:
              - openstack/neutron
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - networking-midonet-ml2-tempest-aio:
            voting: false
        - networking-midonet-ml2-tempest-multinode:
            voting: false
        - networking-midonet-ml2-grenade:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - openstack-tox-py36:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
        - openstack-tox-py38:
            voting: false
            required-projects:
              - openstack/neutron-vpnaas
              - openstack/neutron-dynamic-routing
              - x/networking-l2gw
              - openstack/tap-as-a-service
